nginx-ssl-proxy:
  image: danieldent/nginx-ssl-proxy
  restart: always
  environment:
    UPSTREAM: 127.0.0.1:8080
    SERVERNAME: www.badoumbam.com
    EXTRANAMES: www.demo.badoumbam.com
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/letsencrypt"